Public Class DTO_CM
    Public Property id_Matrix As Integer
    Public Property Org_Empresa As Double
    Public Property Nr_Cartao As String
    Public Property Cod_Fila_Atual As Double
    Public Property Fila_Atual As String
    Public Property Cod_Fila_Ant As Double
    Public Property Fila_Ant As String
    Public Property Grupo_Regra As Double
    Public Property Regra As Double
    Public Property Score As Double
    Public Property DT_Transacao As Date
    Public Property Valor_Local As Double
    Public Property Valor_Faturado As Double
    Public Property POS As String
    Public Property Resp As String
    Public Property MCC As Double
    Public Property Campo16 As String
    Public Property Cod_Estab As String
    Public Property Estab As String
    Public Property Cidade_Estab As String
    Public Property UF_Estab As String
    Public Property País As String
    Public Property Moeda As String
    Public Property NR_POS As String
    Public Property Token_requestor_ID As Double
    Public Property Flag_Token As String
    Public Property Tipo_Mensagem As String
    Public Property Token_Provisioning_Score As Double
    Public Property Device_Type As Double
    Public Property Token_Account_Score As Double
    Public Property Token_Device_Score As Double
    Public Property Token_Reason_Code As String
    Public Property Device_Number As String
    Public Property IP_Address As String
    Public Property ID_Requisitante_Token As String
    Public Property Nivel_Segurança_Token As String
    Public Property PAN As String
    Public Property Token_PSN As String
    Public Property Token_Expiration_Dat As String
    Public Property Token_Status As String
    Public Property Token_Cryptogram_Verification_Results As String
    Public Property EMV_Token_Cryptogram_Verificarion_Results As String
    Public Property Token_Constraints_Verification_Status As String
    Public Property Transaction_Date_Time_Constraint As String
    Public Property Transaction_Amount_Constraint As String
    Public Property Usage_Constraint As String
    Public Property Token_ATC_Verification_Result As String
    Public Property CVE2_Token_Cryptogram_Verification_Status As String
    Public Property MCC_Constraints As String
    Public Property Type_Process As String
    Public Property Cliente_UHV As String
    Public Property Resposta As String
    Public Property Data_Registro As Date
    Public Property Usuario_Resp As String
    Public Property dataImportacao As Date
    Public Property idImportador As String

End Class
